### ISSUE TITLE
Some questions about your last paper

### ISSUE THREAD

**Issue by 764483** [cheerss/CrossFormer#13]
Dear author, I have read your article recently:'Accelerate CNNs from Three Dimensions: A Comprehensive Pruning Framework', and I am particularly interested in your article. Do you have an open source plan? Thank you for your answer.

**Comment by cheerss** [comment]
Sorry, but no specific plan yet. The code for that pape is still in a messy, containing too many discarded changes and tries. I am too busy to deal with it T_T T_T T_T

**Comment by 764483** [comment]
Ok, thank you very much for your reply. Wish you can finish your work soon.
