### ISSUE TITLE
KeyError: "EncoderDecoder: 'CrossFormer_L is not in the backbone registry'"

### ISSUE THREAD

**Issue by yangyang117** [cheerss/CrossFormer#2]
when i run the program, there is a mistake:
 
KeyError: "EncoderDecoder: 'CrossFormer_L is not in the backbone registry'"

how can i registry this?

**Comment by cheerss** [comment]
Hi @yangyang117, 

It depends. You may wish to provide the specific task (e.g., classification/detection/segmentations, etc.) and the exact command you run.

**Comment by yangyang117** [comment]
hi, i was running the segmentations(/CrossFormer/segmentation). others are not runned.

**Comment by cheerss** [comment]
@yangyang117 

A strange error, CrossFormer_L should be registered automatically.
Could you please provide the command you run?

**Comment by yangyang117** [comment]
i just run it by pycharm step by step. which file including the register program, i could run it by myself.

**Comment by yangyang117** [comment]
I found it. thank you for your help.
