### ISSUE TITLE
Can I use this network as my feature extraction network

### ISSUE THREAD

**Issue by XIAN-XIAN-X** [cheerss/CrossFormer#23]
Since the input resolution of my task weight is not 224, can I still load the imagenet pre-training weights

**Comment by cheerss** [comment]
Of course, but empirically, finetuning a few epochs with a target resolution would be better.

**Comment by XIAN-XIAN-X** [comment]
请问假设我的图片分辨率是192*640，那么我应该把网络中的self.input_resolution改成192*640吗？如果可以这样改的话我加载本文提供的inagenet预训练权重会不会不匹配呢？
