### ISSUE TITLE
Does CrossFormer require a fixed input size?

### ISSUE THREAD

**Issue by amobiny** [cheerss/CrossFormer#3]
Hi there and thanks for the nice work.
I'm currently trying to use CrossFormer_B as my backbone in detection/instance_segmentation.
I've noticed that we need to define the img_size in the backbone configs. However, defining that can be limiting in the sense that we usually use cropping augmentations during training, or multi-scale inference at test time. Is there any way to keep these methods working with the current implementation?

I'll copy the related part of my config file down here:

model = dict(
    type='CascadeRCNN',
    pretrained=None,
    backbone=dict(
        type='CrossFormer',
        img_size=[3840, 1920],
        patch_size=[4, 8, 16, 32],
        in_chans=3,
        num_classes=7,
        embed_dim=96,
        depths=[2, 2, 18, 2],
        num_heads=[3, 6, 12, 24],
        group_size=[7, 7, 7, 7],
        crs_interval=[8, 4, 2, 1],
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.0,
        drop_path_rate=0.3,
        patch_norm=True,
        use_checkpoint=False,
        merge_size=[[2, 4], [2, 4], [2, 4]]),

...
...

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(
        type='Resize',
        img_scale=[(3840, 1080), (3840, 1560)],
        multiscale_mode='range',
        keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.0),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]

...
...

Thanks,

**Comment by cheerss** [comment]
@amobiny  

CrossFormer supports dynamic input size naturally, and you do not need to do any changes.

The "img_size" in config files is only used to compute the FLOPs under the given image size. It will never affect the training/testing of models. You may wish to verify our claim by scanning all "img_size" in this [file](https://github.com/cheerss/CrossFormer/blob/main/models/crossformer_backbone.py). :)

Thanks for your notice, and we will supplement this comment in our config files.
