### ISSUE TITLE
some question about the different usage of CEL between papers and your codes

### ISSUE THREAD

**Issue by lovedoubledan** [cheerss/CrossFormer#7]
I have read your paper and noticed that CEL was used in all stages.
But I found in codes that you used it in the first stage only.
Am I mistaken?

**Comment by cheerss** [comment]
Both `PatchEmbed` and `PatchMerging` are CEL layers. `PatchEmbed` is used in the first stage, while `PatchMerging` is for others.

**Comment by lovedoubledan** [comment]
Thanks.

**Comment by yutongred** [comment]
Seems like your PatchMerging Module need args passing in[ _crossformer.py line 553_](https://github.com/cheerss/CrossFormer/blob/main/models/crossformer.py) [e.g.: dim is not defined?]
