### ISSUE TITLE
could you provide the train log of segmentation and detection?

### ISSUE THREAD

**Issue by 1104662797** [cheerss/CrossFormer#8]

**Comment by cheerss** [comment]
Sorry, we do not think it is necessary to add these logs into the code repository, while we could help you if you have any problem in training these models.

**Comment by 1104662797** [comment]
Thanks for your reply. I run the model on 2 rtx3090,but the result is very poor.

**Comment by 1104662797** [comment]
不好意思，我看您是浙大的，我就直接使用中文了。我本来再做pvt的segmentation和detection实验，但是效果十分离谱，我使用了相同的环境，除开pytorch版本不一样（由于我使用3090，导致我只能使用cuda11.1以上）。我注意到你们的实验中也包含这两项，也对pvt进行了实验，我也使用了你们的代码进行尝试，但是仍然不work。 所以我想知道，我该如何解决这个问题，或者你能告诉我你的pytorch版本和对应的cuda版本么？

**Comment by cheerss** [comment]
Thanks for your interest ;). For those non-native speakers, I'll still keep using English.

I guess it has nothing to do with CUDA or pytorch version. Mine are CUDA 10.2/11.2 (both are tested) and pytorch 1.7.0.

I think the most possible cause is the pretrained model. You need a model pretrained on ImageNet, and fine-tune it on detection or segmentation tasks.

Take CrossFormer as an example, you could download the pretrained model according to the guide [here](https://github.com/cheerss/CrossFormer/blob/main/README.md). The training log will tell you whether the pretrained model is loaded correctly.

By the way, if you use our code, the following step is essential (sorry, it looks a bit inconvenient now, and we will update it later):

```
import torch
ckpt = torch.load("crossformer-s.pth") ## load classification checkpoint
torch.save(ckpt["model"], "backbone-crossformer-s.pth") ## only model weights are needed
```
Please see the README [here](https://github.com/cheerss/CrossFormer/blob/main/detection/README.md) for more details.

If the pretrained model is loaded correctly, there will be very few `unexpected keys` and `missing keys` in the fine-tuning logs.

**Comment by 1104662797** [comment]
Thanks for your reply, I detail check the fine-tuning logs, I found that the model do not load correctly in every time.  Even the load model correctly, the mIoU probably be very poor, I have solved this by pytorch1.8.0+cuda11.1. Thanks very much
